# coding = utf - 8
from selenium import webdriver
from yingxiaoluodiye.moudle_17.common.log import Logger
from yingxiaoluodiye.moudle_17.pages.basepage import BasePage


mylogger = Logger(logger = "营销17#模板首页").getlog()

class HomePage(BasePage):
    def tuijiankuang_test(self):
        self.click_by_xpath('//*[@id="list"]/ul/li[2]/span[1]/a[1]/img')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[2]/span[1]/a[2]')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[2]/span[2]/a[1]/img')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[2]/span[2]/a[2]')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[2]/span[3]/a[1]/img')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[2]/span[3]/a[2]')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[2]/span[4]/a[1]/img')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[2]/span[4]/a[2]')
        self.sleep(1)
        self.click_by_xpath('//*[@id="next"]')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[3]/span[1]/a[1]/img')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[3]/span[1]/a[2]')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[3]/span[2]/a[1]/img')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[3]/span[2]/a[2]')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[3]/span[3]/a[1]/img')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[3]/span[3]/a[2]')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[3]/span[4]/a[1]/img')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[3]/span[4]/a[2]')
        self.sleep(1)
        self.click_by_xpath('//*[@id="next"]')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[4]/span[1]/a[1]/img')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[4]/span[1]/a[2]')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[4]/span[2]/a[1]/img')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[4]/span[2]/a[2]')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[4]/span[3]/a[1]/img')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[4]/span[3]/a[2]')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[4]/span[4]/a[1]/img')
        self.sleep(1)
        self.click_by_xpath('//*[@id="list"]/ul/li[4]/span[4]/a[2]')
        self.sleep(1)
        self.click_by_xpath('//*[@id="bzPopBox"]/div/div[3]/div/div[2]/div/div/ul/li/span[1]/a[1]/img')
        self.sleep(1)
        self.click_by_xpath('//*[@id="bzPopBox"]/div/div[3]/div/div[2]/div/div/ul/li/span[1]/a[2]')
        self.sleep(1)
        self.click_by_xpath('//*[@id="bzPopBox"]/div/div[3]/div/div[2]/div/div/ul/li/span[2]/a[1]/img')
        self.sleep(1)
        self.click_by_xpath('//*[@id="bzPopBox"]/div/div[3]/div/div[2]/div/div/ul/li/span[2]/a[2]')
        self.sleep(1)
        self.click_by_xpath('//*[@id="bzPopBox"]/div/div[3]/div/div[2]/div/div/ul/li/span[3]/a[1]/img')
        self.sleep(1)
        self.click_by_xpath('//*[@id="bzPopBox"]/div/div[3]/div/div[2]/div/div/ul/li/span[3]/a[2]')
        self.sleep(1)
        self.click_by_xpath('//*[@id="bzPopBox"]/div/div[3]/div/div[2]/div/div/ul/li/span[4]/a[1]/img')
        self.sleep(1)
        self.click_by_xpath('//*[@id="bzPopBox"]/div/div[3]/div/div[2]/div/div/ul/li/span[4]/a[2]')
        self.sleep(1)

    def tuijiankuang_close(self):
        self.click_by_xpath('//*[@id="bzPopBox"]/div/div[1]/a')

    def homepage_test(self):
        self.click_by_xpath('//*[@id="header"]/div[1]/img')
        self.tuijiankuang_test()
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('//*[@id="header"]/div[2]/h1')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('//*[@id="header"]/div[2]/p[1]')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('//*[@id="J_download1"]')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('//*[@id="header"]/div[2]/p[2]')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[2]/div/ul/li[1]/h3')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[2]/div/ul/li[1]/div/span')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[2]/div/ul/li[3]/h3')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[2]/div/ul/li[3]/div/span')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[2]/div/ul/li[2]/h3')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[2]/div/ul/li[2]/div/img')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[2]/div/ul/li[4]/h3')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[2]/div/ul/li[4]/div/span')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[3]/div[1]/ul/li[1]/dl/dd/h2')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[3]/div[1]/ul/li[1]/dl/dd/p')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[3]/div[1]/ul/li[1]/dl/dt/img')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[3]/div[1]/ul/li[2]/dl/dt/img')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[3]/div[1]/ul/li[2]/dl/dd/h2')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[3]/div[1]/ul/li[2]/dl/dd/p')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[3]/div[1]/ul/li[3]/dl/dd/h2')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[3]/div[1]/ul/li[3]/dl/dd/p')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[3]/div[1]/ul/li[3]/dl/dt/img')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[3]/div[2]/div/h1')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[3]/div[2]/div/p[1]')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('//*[@id="J_download2"]')
        self.tuijiankuang_close()
        self.sleep(1)
        self.click_by_xpath('/html/body/div[2]/div[3]/div[2]/div/p[2]')
        self.tuijiankuang_close()
        self.sleep(1)

if __name__ == "__main__":
    hpage = HomePage(driver = webdriver.Chrome(), showid = 17)
    hpage.start_browser()
    hpage.sleep(2)
    hpage.homepage_test()
    hpage.sleep(2)
    hpage.quit_browser()